<a href="https://colab.research.google.com/github/tugcecicekli/Math-2024-25-Winter/blob/main/Basic_Operations_on_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Matrix Operations

### Matrix Addition

Let $A=[a_{ij}]$ and $B=[b_{ij}]$ be two matrices of dimensions $m \times n$. Then the sum of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times n$, where $c_{ij}=a_{ij}+b_{ij}$.

### Matrix Scalar Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and let $k$ be a scalar. Then the product of matrix $A$ and scalar $k$ is the matrix $B=[b_{ij}]$ of dimensions $m \times n$, where $b_{ij}=k \cdot a_{ij}$.

### Matrix Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and $B=[b_{ij}]$ be a matrix of dimensions $n \times p$. Then the product of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times p$, where $c_{ij}=\sum_{k=1}^{n} a_{ik} \cdot b_{kj}$.


### Example 1

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.
Then the sum of matrices $A$ and $B$ is

$$
C=
A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix}=\begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}.
$$

### Example 2

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $k=2$.

Then the product of matrix $A$ and scalar $k$ is

$$
B=
k \cdot A=2 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}=\begin{bmatrix} 2*1 & 2*2 \\ 2*3 & 2*4 \end{bmatrix}=\begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}.
$$

### Example 3

Let
$A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
and
$B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

Then the product of matrices $A$ and $B$ is

$$
C=
A \cdot B=\begin{bmatrix} 1*5+2*7 & 1*6+2*8 \\ 3*5+4*7 & 3*6+4*8 \end{bmatrix}=\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}.
$$

In [ ]:
# Example 1: Matrix addition in sympy
import sympy as sp

A=sp.Matrix([[1,2],[3,4]])
B=sp.Matrix([[5,6],[7,8]])
A # display matrix A

Matrix([
[1, 2],
[3, 4]])

In [ ]:
B # display matrix B

Matrix([
[5, 6],
[7, 8]])

In [ ]:
sp.Matrix([[6,8],[10,12]])==A+B # verify matrix addition

True

In [ ]:
# Example 2: Scalar multiplication
A=sp.Matrix([[1,2],[3,4]]) # define matrix A

sp.Matrix([[2,4],[6,8]])==2*A # verify scalar multiplication

In [ ]:
# Example 3: Multiplication of two matrices

A=sp.Matrix([[1,2],[3,4]]) # define matrix A
B=sp.Matrix([[5,6],[7,8]]) # define matrix B

sp.Matrix([[19,22],[43,50]])==A*B # verify matrix multiplication

### Necessary Condition for Matrix Multiplication

Remember that matrices can have different numbers of rows and columns.

To multiply two matrices $A_{m \times n}$ and $B_{n \times k}$, where $A$ has dimensions $m \times n$ and $B$ has dimensions $n \times k$, the number of columns of matrix $A$ must equal the number of rows of matrix $B$. Otherwise, matrix multiplication is not possible.

$$
A_{m \times n} \cdot B_{n \times k} = C_{m \times k}
$$

For example, if $A_{3 \times 3}$ and $B_{3 \times 3}$, then the resulting matrix $C_{3 \times 3}$.

<img src="https://www.mscroggs.co.uk/img/full/multiply_matrices.gif" alt="Matrix Multiplication GIF" width="400">

### Matrix Multiplication is Not Commutative

Matrix multiplication is not commutative, i.e., in general $A \cdot B \neq B \cdot A$.

In [ ]:
# Example of multiplying rectangular matrices
import sympy as sp
A=sp.Matrix([[1,2],[3,4],[5,6]]) # define matrix A_{3 x 2}
B=sp.Matrix([[1,2,3],[4,5,6]]) # define matrix B_{2 x 3}
C=sp.Matrix([[9,12,15],[19,26,33],[29,40,51]]) # define matrix C_{3 x 3}

A*B # multiply matrices A and B to get a 3x3 matrix

In [ ]:
B*A # multiply matrices B and A to get a 2x2 matrix

In [ ]:
B*C # multiply matrices B and C to get a 2x3 matrix

---
## Exercises for Students (old version)

1. Calculate the sum of matrices $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

2. Calculate the product of matrix $A=\begin{bmatrix} 4 & 2 \\ 12 & 4 \end{bmatrix}$ and scalar $k=\frac{1}{4}$.

3. Calculate the products $A\cdot B$ and $B \cdot A$ for matrices $A=\begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 4 & 1 \\ 6 & 4 \end{bmatrix}$.

In [ ]:
import numpy as np

c= np.array([[6,8],[10,12]])

print(c)

[[ 6  8]
 [10 12]]


In [ ]:
import sympy as sp

A = sp.Matrix([[4,2],[12,4]])
k= sp.Rational(1,4) # Represents 1\4 as a rational number
B= k*A

In [ ]:
import numpy as np
C=np.array([[24,11],[32,18]])
D=np.array([[14,12],[26,28]])
print("Matrix C:")
print(C)

print("Matrix D:")
print(D)

Matrix C:
[[24 11]
 [32 18]]
Matrix D:
[[14 12]
 [26 28]]



## Exercises for Students (new version)

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1. Calculate: $\mathbf{A}+\mathbf{B}$;  $\mathbf{B}-\mathbf{A}$;  $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2. Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$, and $4\mathbf{D}$.

3. Calculate the products $\mathbf{A}\cdot \mathbf{B}$; $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$; $\mathbf{D} \cdot \mathbf{E}$.

1. a) $A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+ 7& 4+ 8\end{bmatrix}=\begin{bmatrix} 6&8\\10&12\end{bmatrix}$


1. b) $B-A=\begin{bmatrix} 5-1 & 6-2 \\ 7-3 & 8-4 \end{bmatrix}=\begin{bmatrix} 4&4 \\4&4\end{bmatrix}$


1. c) $A+C=\begin{bmatrix} 1-1 & 2+2 \\ 3+3 & 4+0 \end{bmatrix}=\begin{bmatrix} 0&2\\6&4\end{bmatrix}$


1. d) D+E are not the same dimension, you can't add two matrices if they don't have the same dimension.

 2. a) $\frac{1}{2}\mathbf{A}=\frac{1}{2} \begin{pmatrix} 1&2 \\ 3&4 \end{pmatrix}=\begin{pmatrix} \frac{1}{2}*1 & \frac{1}{2}*2 \\ \frac{1}{2}*3 & \frac{1}{2}*4\end{pmatrix}=\begin{pmatrix} \frac{1}{2} & 1\\ \frac{3}{2} &2\end{pmatrix}$


2. b) $2B=2\begin{pmatrix} 5&6\\7&8\end{pmatrix}=\begin{pmatrix} 2*5 & 2*6 \\ 2*7&2*8\end{pmatrix}=\begin{pmatrix} 10&12\\14&16\end{pmatrix}$


2. c) $-3C=-3\begin{pmatrix} -1&2\\3&0\end{pmatrix}=\begin{pmatrix} (-3)*(-1) & (-3)*2\\ (-3)*3 & (-3)*0\end{pmatrix}=\begin{pmatrix} 3&-6\\ -9&0\end{pmatrix}$


2. d) $4B=4\begin{pmatrix} -1&2&3\\4&0&6\end{pmatrix}=\begin{pmatrix}4*(-1)&4*2&4*3\\4*4&4*0&4*6\end{pmatrix}=\begin{pmatrix} -4&8&12\\16&0&24\end{pmatrix}$



3. a) $A⋅B=\begin{bmatrix} 1&2 \\ 3&4 \end{bmatrix} ⋅\begin{bmatrix} 5&6 \\ 7&8 \end{bmatrix}= \begin{bmatrix} 1*5 + 2*7 & 1*6 + 2*8\\ 3*5 + 4*7 & 3*6 + 4*8 \end{bmatrix}=\begin{bmatrix} 5+12 & 6+16 \\ 15+28 & 18+32 \end{bmatrix}=\begin{bmatrix} 17 & 22\\ 43 &50 \end{bmatrix}$


3. b) $B⋅A=\begin{bmatrix} 5&6 \\ 7&8 \end{bmatrix} ⋅\begin{bmatrix} 1&2 \\ 3&4 \end{bmatrix}=\begin{bmatrix} 5*1 + 6*3 & 5*2 + 6*4 \\ 7*1 + 8*3 & 7*2 + 8*4 \end{bmatrix}=\begin{bmatrix} 5+18 & 10+24 \\ 7+24 & 14+32 \end{bmatrix}=\begin{bmatrix} 23 & 32 \\ 31 & 46\end{bmatrix}$


3. c) $A⋅D=\begin{bmatrix} 1&2\\3&4\end{bmatrix} ⋅\begin{bmatrix} -1&2&3\\4&0&6\end{bmatrix}=\begin{bmatrix} 1*(-1)+2*4 & 1*2+2*0 & 1*3+2*6 \\3*(-1)+4*4 & 3*2+4*0 & 3*3+4*6\end{bmatrix}=\begin{bmatrix} (-1)+8 & 2+0 & 3+12\\(-3)+16&6+0&9+24\end{bmatrix}=\begin{bmatrix} 7&2&15\\13&6&33\end{bmatrix}$


3. d) $D⋅E=\begin{bmatrix} -1&2&3\\4&0&6\end{bmatrix}⋅\begin{bmatrix} 1&2\\4&5\\7&8\end{bmatrix}=\begin{bmatrix} -1*1+2*4+3*7&-1*2+2*5+3*8\\4*1+0*4+6*7&4*2+0*5+6*8\end{bmatrix}=\begin{bmatrix} -1+8+21&-2+10+24\\4+0+42&8+0+48\end{bmatrix}=\begin{bmatrix} 28&32\\46&56\end{bmatrix}$