<a href="https://colab.research.google.com/github/tugcecicekli/Math-2024-25-Winter/blob/main/Copy_of_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix


```markdown
# Matrix Addition

Matrix addition is the process of adding two matrices by adding their corresponding elements. To perform matrix addition, the two matrices must have the same dimensions (i.e., the same number of rows and columns).

## Key Points About Matrix Addition
1. **Same Dimensions Required**: Matrix addition is only defined for matrices with the same dimensions.
2. **Element-Wise Operation**: Each element in the resulting matrix is the sum of the corresponding elements from the two matrices.

### Mathematical Representation
Let \( A \) and \( B \) be two matrices with dimensions \( m \times n \):
\[
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix},
\quad
B =
\begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1n} \\
b_{21} & b_{22} & \cdots & b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
b_{m1} & b_{m2} & \cdots & b_{mn}
\end{bmatrix}
\]

Their sum \( C = A + B \) is:
\[
C =
\begin{bmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}
\end{bmatrix}
\]

### Example
Given two matrices:
\[
A =
\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & 5
\end{bmatrix},
\quad
B =
\begin{bmatrix}
7 & 8 & 9 \\
0 & 2 & 4
\end{bmatrix}
\]

Their sum is:
\[
C = A + B =
\begin{bmatrix}
2+7 & 4+8 & 6+9 \\
1+0 & 3+2 & 5+4
\end{bmatrix}
=
\begin{bmatrix}
9 & 12 & 15 \\
1 & 5 & 9
\end{bmatrix}
\]

### Python Code for Matrix Addition
```python
# Import the numpy library
import numpy as np

# Define the matrices
A = np.array([[2, 4, 6], [1, 3, 5]])
B = np.array([[7, 8, 9], [0, 2, 4]])

# Perform matrix addition
C = A + B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nSum of A and B (Matrix C):")
print(C)
```
```

# Python Commands

```markdown
# Introduction to Python Commands

Here is a table of commonly used Python commands, their descriptions, and examples to help you get started with Python programming.

| **Command**         | **Description**                                      | **Example**                                               |
|----------------------|------------------------------------------------------|-----------------------------------------------------------|
| `print()`           | Outputs text or variables to the console.            | `print("Hello, World!")` → `Hello, World!`               |
| `type()`            | Returns the type of a variable or value.             | `type(5)` → `<class 'int'>`                              |
| `input()`           | Takes user input as a string.                        | `name = input("Enter your name: ")`                      |
| `len()`             | Returns the length of a string, list, or other iterable.| `len("Python")` → `6`                                   |
| `int()`             | Converts a value to an integer.                      | `int("42")` → `42`                                       |
| `float()`           | Converts a value to a floating-point number.         | `float("3.14")` → `3.14`                                 |
| `str()`             | Converts a value to a string.                        | `str(123)` → `"123"`                                     |
| `list()`            | Converts an iterable into a list.                    | `list("abc")` → `['a', 'b', 'c']`                        |
| `range()`           | Generates a sequence of numbers.                     | `list(range(5))` → `[0, 1, 2, 3, 4]`                     |
| `for` loop          | Iterates over items in a sequence.                   | `for i in range(3): print(i)` → `0\n1\n2`                |
| `if` statement      | Conditional statement to execute code if condition is true.| `if 5 > 3: print("Yes")` → `Yes`                      |
| `def`               | Defines a function.                                  | `def greet(): print("Hello")`                            |
| `import`            | Imports a module into your program.                  | `import math`                                            |
| `math.sqrt()`       | Computes the square root of a number (requires `math`).| `math.sqrt(16)` → `4.0`                                  |
| `open()`            | Opens a file.                                        | `file = open("example.txt", "r")`                        |
| `with` statement    | Manages resources like files more cleanly.           | `with open("example.txt", "r") as f: print(f.read())`    |
| `append()`          | Adds an item to a list.                              | `my_list = []; my_list.append(10)` → `[10]`             |
| `len()`             | Returns the length of a collection.                  | `len([1, 2, 3])` → `3`                                   |
| `help()`            | Provides help for a function or module.              | `help(print)`                                            |

Each of these commands is fundamental to understanding Python and is useful for a variety of tasks.
```

# C++ and Python Commands

Here’s a table comparing basic commands in C++ and Python:

| **Action**               | **C++ Command**                            | **Python Command**                         | **Description**                                       |
|--------------------------|---------------------------------------------|--------------------------------------------|-------------------------------------------------------|
| Print output             | `std::cout << "Hello, World!";`            | `print("Hello, World!")`                   | Displays output to the console.                      |
| Declare a variable       | `int x = 5;`                               | `x = 5`                                    | Declares a variable and assigns a value.             |
| Input from user          | `std::cin >> x;`                           | `x = input("Enter value: ")`               | Takes input from the user.                           |
| Check data type          | `typeid(x).name()`                         | `type(x)`                                  | Gets the type of a variable.                         |
| Length of a string       | `std::string str = "Hello"; str.size();`    | `len("Hello")`                             | Gets the length of a string or collection.           |
| Loop (for)               | `for (int i = 0; i < 5; i++) {}`           | `for i in range(5):`                       | Iterates over a range of values.                     |
| Loop (while)             | `while (i < 5) {}`                         | `while i < 5:`                             | Loops while a condition is true.                     |
| Conditional (if)         | `if (x > 0) {}`                            | `if x > 0:`                                | Executes code based on a condition.                  |
| Function definition      | `int add(int a, int b) { return a + b; }`  | `def add(a, b): return a + b`              | Defines a reusable block of code.                    |
| Import library           | `#include <cmath>`                         | `import math`                              | Imports a library or module.                         |
| Square root              | `std::sqrt(16)`                            | `math.sqrt(16)`                            | Calculates the square root.                          |
| Append to list/array     | `std::vector<int> v; v.push_back(10);`     | `my_list = []; my_list.append(10)`         | Adds an element to a list or vector.                 |
| Open a file              | `std::ifstream file("example.txt");`       | `file = open("example.txt", "r")`          | Opens a file for reading or writing.                 |
| Read from file           | `std::getline(file, line);`                | `file.read()`                              | Reads content from a file.                           |
| Comment (single-line)    | `// This is a comment`                     | `# This is a comment`                      | Adds a single-line comment.                          |
| Comment (multi-line)     | `/* Multi-line comment */`                 | `''' Multi-line comment '''`               | Adds a multi-line comment.                           |
| Exit program             | `return 0;`                                | `exit()`                                   | Exits the program.                                   |

This table highlights basic similarities and differences between C++ and Python commands for common programming tasks.

# Basic Matrix Operations

In [ ]:
# Exercise 1: Matrix addition
import sympy as sp

A=sp.Matrix([[1,2],[3,4]])
B=sp.Matrix([[5,6],[7,8]])
A+B # add matrices A and B

Matrix([
[ 6,  8],
[10, 12]])

In [ ]:
# Exercise 2: Multiplication of a scalar and matrix
import sympy as sp

A=sp.Matrix([[4,2],[12,4]]) # define matrix A
k=sp.Rational(1,4) # define scalar k
A*k # multiply matrix A and scalar k


Matrix([
[1, 1/2],
[3,   1]])

## Exercises for Students (old version)

1. Calculate the sum of matrices $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

2. Calculate the product of matrix $A=\begin{bmatrix} 4 & 2 \\ 12 & 4 \end{bmatrix}$ and scalar $k=\frac{1}{4}$.

3. Calculate the products $A\cdot B$ and $B \cdot A$ for matrices $A=\begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 4 & 1 \\ 6 & 4 \end{bmatrix}$.

In [ ]:
import numpy as np

c = np.array([[6,8],[10,12]])
print(c)


[[ 6  8]
 [10 12]]


In [ ]:
import sympy as sp
A=sp.Matrix([[4,2],[12,4]])
k=sp.Rational(1,4) # Represents 1\4 as a rational number
B=k*A
print(B)


Matrix([[1, 1/2], [3, 1]])


In [ ]:
import numpy as np
C=np.array([[24,11],[32,18]])
D=np.array([[14,12],[26,28]])
print("Matrix C:")
print(C)

print("Matrix D:")
print(D)

Matrix C:
[[24 11]
 [32 18]]
Matrix D:
[[14 12]
 [26 28]]


## Exercises for Students (new version)

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1. Calculate: $\mathbf{A}+\mathbf{B}$;  $\mathbf{B}-\mathbf{A}$;  $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2. Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$, and $4\mathbf{D}$.

3. Calculate the products $\mathbf{A}\cdot \mathbf{B}$; $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$; $\mathbf{D} \cdot \mathbf{E}$.

1. a) $A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+ 7& 4+ 8\end{bmatrix}=\begin{bmatrix} 6&8\\10&12\end{bmatrix}$


1. b) $B-A=\begin{bmatrix} 5-1 & 6-2 \\ 7-3 & 8-4 \end{bmatrix}=\begin{bmatrix} 4&4 \\4&4\end{bmatrix}$


1. c) $A+C=\begin{bmatrix} 1-1 & 2+2 \\ 3+3 & 4+0 \end{bmatrix}=\begin{bmatrix} 0&2\\6&4\end{bmatrix}$


1. d) D+E are not the same dimension, you can't add two matrices if they don't have the same dimension.

2. a) $\frac{1}{2}\mathbf{A}=\frac{1}{2} \begin{pmatrix} 1&2 \\ 3&4 \end{pmatrix}=\begin{pmatrix} \frac{1}{2}*1 & \frac{1}{2}*2 \\ \frac{1}{2}*3 & \frac{1}{2}*4\end{pmatrix}=\begin{pmatrix} \frac{1}{2} & 1\\ \frac{3}{2} &2\end{pmatrix}$


2. b) $2B=2\begin{pmatrix} 5&6\\7&8\end{pmatrix}=\begin{pmatrix} 2*5 & 2*6 \\ 2*7&2*8\end{pmatrix}=\begin{pmatrix} 10&12\\14&16\end{pmatrix}$


2. c) $-3C=-3\begin{pmatrix} -1&2\\3&0\end{pmatrix}=\begin{pmatrix} (-3)*(-1) & (-3)*2\\ (-3)*3 & (-3)*0\end{pmatrix}=\begin{pmatrix} 3&-6\\ -9&0\end{pmatrix}$


2. d) $4B=4\begin{pmatrix} -1&2&3\\4&0&6\end{pmatrix}=\begin{pmatrix}4*(-1)&4*2&4*3\\4*4&4*0&4*6\end{pmatrix}=\begin{pmatrix} -4&8&12\\16&0&24\end{pmatrix}$


3. a) $A⋅B=\begin{bmatrix} 1&2 \\ 3&4 \end{bmatrix} ⋅\begin{bmatrix} 5&6 \\ 7&8 \end{bmatrix}= \begin{bmatrix} 1*5 + 2*7 & 1*6 + 2*8\\ 3*5 + 4*7 & 3*6 + 4*8 \end{bmatrix}=\begin{bmatrix} 5+12 & 6+16 \\ 15+28 & 18+32 \end{bmatrix}=\begin{bmatrix} 17 & 22\\ 43 &50 \end{bmatrix}$


3. b) $B⋅A=\begin{bmatrix} 5&6 \\ 7&8 \end{bmatrix} ⋅\begin{bmatrix} 1&2 \\ 3&4 \end{bmatrix}=\begin{bmatrix} 5*1 + 6*3 & 5*2 + 6*4 \\ 7*1 + 8*3 & 7*2 + 8*4 \end{bmatrix}=\begin{bmatrix} 5+18 & 10+24 \\ 7+24 & 14+32 \end{bmatrix}=\begin{bmatrix} 23 & 32 \\ 31 & 46\end{bmatrix}$


3. c)$A⋅D=\begin{bmatrix} 1&2\\3&4\end{bmatrix} ⋅\begin{bmatrix} -1&2&3\\4&0&6\end{bmatrix}=\begin{bmatrix} 1*(-1)+2*4 & 1*2+2*0 & 1*3+2*6 \\3*(-1)+4*4 & 3*2+4*0 & 3*3+4*6\end{bmatrix}=\begin{bmatrix} (-1)+8 & 2+0 & 3+12\\(-3)+16&6+0&9+24\end{bmatrix}=\begin{bmatrix} 7&2&15\\13&6&33\end{bmatrix}$


3. d) $D⋅E=\begin{bmatrix} -1&2&3\\4&0&6\end{bmatrix}⋅\begin{bmatrix} 1&2\\4&5\\7&8\end{bmatrix}=\begin{bmatrix} -1*1+2*4+3*7&-1*2+2*5+3*8\\4*1+0*4+6*7&4*2+0*5+6*8\end{bmatrix}=\begin{bmatrix} -1+8+21&-2+10+24\\4+0+42&8+0+48\end{bmatrix}=\begin{bmatrix} 28&32\\46&56\end{bmatrix}$

# Determinants of 2x2 and 3x3 matrices

In [ ]:
# prompt: generate multiplication of general matrix 2x2 A  and B 2x2

import sympy as sp
import numpy as np
a,b,c,d,e,f,g,h=sp.symbols('a,b,c,d,e,f,g,h')

# Define matrices A and B
A = sp.Matrix([[a, b], [c, d]])
B = sp.Matrix([[e, f], [g, h]])

# Calculate the matrix product A * B


# Print the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Product A * B:")
print(C)

C=A*B
C

Matrix A:
Matrix([[a, b], [c, d]])

Matrix B:
Matrix([[e, f], [g, h]])

Matrix Product A * B:
Matrix([[a*e + b*g, a*f + b*h], [c*e + d*g, c*f + d*h]])


Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

In [ ]:
# prompt: generate multiplication of general matrix 2x2 A  and B 2x2

import sympy as sp
import numpy as np

# Define matrices A and B
A = sp.Matrix([[3,2 ], [2, 4]])
B = sp.Matrix([[4,1 ], [6,4 ]])

# Calculate the matrix product A * B


# Print the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Product A * B:")
print(C)

C=A*B
C

Matrix A:
Matrix([[3, 2], [2, 4]])

Matrix B:
Matrix([[4, 1], [6, 4]])

Matrix Product A * B:
Matrix([[a*e + b*g, a*f + b*h], [c*e + d*g, c*f + d*h]])


Matrix([
[24, 11],
[32, 18]])